### PR TITLE
Optimize Docker and Travis

### PR DESCRIPTION
**Pull request by mappuji**
WIP: Optimize Docker and Travis

### CODE REVIEW

**Comment by dogi** [comment]
@mappuji good work ;)

next steps:
- [ ] in the first stage there is no need for google-chrome stuff in both VMs 
- [ ] in the last stage there is no need for npmstuff and google-chrome in all 3 VMs
- [ ] last stage on rpi can fail without raising a flag ... (e.g. when there is no memory left untar error)
- [ ] test stage has no `ngbuildprod.sh` -> do test or remove file

anyhow we will go ahead and merge this PR to solve the kraken instability

**Comment by dogi** [comment]
when tagging

```
db-init-0.0.19
31 MB
3 minutes ago
rpi-0.0.19
18 MB
4 minutes ago
0.0.19
9 MB
4 minutes ago
rpi-0.0.19-v0.0.19-3e627044
18 MB
4 minutes ago
db-init-0.0.19-v0.0.19-3e627044
31 MB
4 minutes ago
0.0.19-v0.0.19-3e627044
9 MB
4 minutes ago
rpi-db-init-0.0.19
30 MB
4 minutes ago
rpi-db-init-0.0.19-v0.0.19-3e627044
30 MB
4 minutes ago
```

**Comment by dogi** [comment]
confirmed

```
docker images
REPOSITORY               TAG                                                   IMAGE ID            CREATED             SIZE
treehouses/planet        rpi-0.0.19                                            828912e786e1        About an hour ago   50.8MB
treehouses/planet        rpi-0.0.19-v0.0.19-3e627044                           828912e786e1        About an hour ago   50.8MB
```

**Comment by dogi** [comment]
hmm

```
docker images
REPOSITORY               TAG                                                   IMAGE ID            CREATED             SIZE
treehouses/planet        rpi-0.0.19                                            828912e786e1        About an hour ago   50.8MB
treehouses/planet        rpi-0.0.19-master-3e627044                            828912e786e1        About an hour ago   50.8MB
treehouses/planet        rpi-0.0.19-v0.0.19-3e627044                           828912e786e1        About an hour ago   50.8MB
```

apparently they are the same
is that because the code of app did not change
just some peripheral stuff

**Comment by dogi** [comment]
https://www.raspberrypi.org/downloads/raspbian/

**Comment by lmmrssa** [comment]
During trying to setup latest version on desktop, found that latest tag is not getting the version commit. And looking after the docker images this is what it shows. 
NOTE: docker pull of latest is showing upto date.

screen shot 2018-03-16 at 17 19 49

@mappuji @dogi @paulbert please confirm

**Comment by mappuji** [comment]
Thank you for catching this, you're right.

This is the problem 

https://github.com/ole-vi/planet/blob/master/.travis/travis_utils.sh#L115

**Pull request merged**
