### PR TITLE
[#310] Added grid view (connects #310)

### PR DESCRIPTION
**Pull request by yaoxing1990**

### CODE REVIEW

**Comment by yaoxing1990** [comment]
@lmmrssa @paulbert It seems that the inner organization in mat-grid-tile is not properly implemented. Could you give some guidance? 
capture

**Comment by lmmrssa** [comment]
could you point to the design you tried to implement. you are forcing image ratio to change instead it should be image with that ratio not squeezed one. Also you do not have any margin or padding between two sections title and rating.

**Comment by yaoxing1990** [comment]
@lmmrssa I want to implement [Grid List View](https://material.angular.io/components/grid-list/overview), to replace the original [mat table](https://material.angular.io/components/table/overview). And I did not figure out how to give appropriate positions.

**Comment by lmmrssa** [comment]
@yaoxing1990 issue you tried to work on was not meant to implement grid view. It was just supposed to update the rating section of list view.
Grid view will require different issue to work on. Also it will not replace the mat-table view instead it should be two switchable views (Grid/List)

**Comment by paulbert** [comment]
Closing since this was not the intended goal of the issue, and we won't be implementing a grid view in the near future.

**Pull request closed without merging**
